"""
Constants for US address parsing and normalization.

This module contains mappings for:
- Directional prefixes/suffixes (North, South, etc.)
- Street type qualifiers (Alternate, Business, etc.)
- Street type prefixes and suffixes with canonical abbreviations
- US state and territory names and abbreviations

Ported from Ruby Geocoder::US constants.
"""

import re
from typing import Dict, Pattern


class TwoWayMap(dict):
    """
    A two-way mapping dictionary that allows lookup by key or value.
    Supports case-insensitive lookups and builds a regex pattern for matching.
    """
    
    def __init__(self, mapping: Dict[str, str]):
        super().__init__()
        # Add original mappings
        for k, v in mapping.items():
            self[k] = v
        # Add lowercase versions
        for k, v in list(self.items()):
            self[k.lower()] = self.get(k, v)
            self[v.lower()] = v
        # Build regex pattern
        all_terms = list(mapping.keys()) + list(mapping.values())
        self.regexp = re.compile(
            r'\b(' + '|'.join(re.escape(term) for term in all_terms) + r')\b',
            re.IGNORECASE
        )
    
    def get_case_insensitive(self, key: str, default=None):
        """Get value with case-insensitive lookup."""
        return self.get(key.lower(), default)


# Directional prefixes and suffixes
# Maps compass directions (English and Spanish) to 1-2 letter abbreviations
DIRECTIONAL = TwoWayMap({
    "North": "N",
    "South": "S",
    "East": "E",
    "West": "W",
    "Northeast": "NE",
    "Northwest": "NW",
    "Southeast": "SE",
    "Southwest": "SW",
    "Norte": "N",
    "Sur": "S",
    "Este": "E",
    "Oeste": "O",
    "Noreste": "NE",
    "Noroeste": "NO",
    "Sudeste": "SE",
    "Sudoeste": "SO"
})


# Prefix qualifiers (e.g., "Alternate Main Street")
PREFIX_QUALIFIER = TwoWayMap({
    "Alternate": "Alt",
    "Business": "Bus",
    "Bypass": "Byp",
    "Extended": "Exd",
    "Historic": "Hst",
    "Loop": "Lp",
    "Old": "Old",
    "Private": "Pvt",
    "Public": "Pub",
    "Spur": "Spr",
})


# Suffix qualifiers (e.g., "Main Street Extension")
SUFFIX_QUALIFIER = TwoWayMap({
    "Access": "Acc",
    "Alternate": "Alt",
    "Business": "Bus",
    "Bypass": "Byp",
    "Connector": "Con",
    "Extended": "Exd",
    "Extension": "Exn",
    "Loop": "Lp",
    "Private": "Pvt",
    "Public": "Pub",
    "Scenic": "Scn",
    "Spur": "Spr",
    "Ramp": "Rmp",
    "Underpass": "Unp",
    "Overpass": "Ovp",
})


# Canonical prefix street types from TIGER/Line documentation
PREFIX_CANONICAL = {
    "Arcade": "Arc",
    "Autopista": "Autopista",
    "Avenida": "Ave",
    "Avenue": "Ave",
    "Boulevard": "Blvd",
    "Bulevar": "Bulevar",
    "Bureau of Indian Affairs Highway": "BIA Hwy",
    "Bureau of Indian Affairs Road": "BIA Rd",
    "Bureau of Indian Affairs Route": "BIA Rte",
    "Bureau of Land Management Road": "BLM Rd",
    "Bypass": "Byp",
    "Calle": "Cll",
    "Calleja": "Calleja",
    "Callejón": "Callejón",
    "Caminito": "Cmt",
    "Camino": "Cam",
    "Carretera": "Carr",
    "Cerrada": "Cer",
    "Círculo": "Cír",
    "Commons": "Cmns",
    "Corte": "Corte",
    "County Highway": "Co Hwy",
    "County Lane": "Co Ln",
    "County Road": "Co Rd",
    "County Route": "Co Rte",
    "County State Aid Highway": "Co St Aid Hwy",
    "County Trunk Highway": "Co Trunk Hwy",
    "County Trunk Road": "Co Trunk Rd",
    "Court": "Ct",
    "Delta Road": "Delta Rd",
    "District of Columbia Highway": "DC Hwy",
    "Driveway": "Driveway",
    "Entrada": "Ent",
    "Expreso": "Expreso",
    "Expressway": "Expy",
    "Farm Road": "Farm Rd",
    "Farm-to-Market Road": "FM",
    "Fire Control Road": "Fire Cntrl Rd",
    "Fire District Road": "Fire Dist Rd",
    "Fire Lane": "Fire Ln",
    "Fire Road": "Fire Rd",
    "Fire Route": "Fire Rte",
    "Fire Trail": "Fire Trl",
    "Forest Highway": "Forest Hwy",
    "Forest Road": "Forest Rd",
    "Forest Route": "Forest Rte",
    "Forest Service Road": "FS Rd",
    "Highway": "Hwy",
    "Indian Route": "Indian Rte",
    "Indian Service Route": "Indian Svc Rte",
    "Interstate Highway": "I-",
    "Lane": "Ln",
    "Logging Road": "Logging Rd",
    "Loop": "Loop",
    "National Forest Development Road": "Nat For Dev Rd",
    "Navajo Service Route": "Navajo Svc Rte",
    "Parish Road": "Parish Rd",
    "Pasaje": "Pasaje",
    "Paseo": "Pso",
    "Passage": "Psge",
    "Placita": "Pla",
    "Plaza": "Plz",
    "Point": "Pt",
    "Puente": "Puente",
    "Ranch Road": "Ranch Rd",
    "Ranch to Market Road": "RM",
    "Reservation Highway": "Resvn Hwy",
    "Road": "Rd",
    "Route": "Rte",
    "Row": "Row",
    "Rue": "Rue",
    "Ruta": "Ruta",
    "Sector": "Sec",
    "Sendero": "Sendero",
    "Service Road": "Svc Rd",
    "Skyway": "Skwy",
    "Square": "Sq",
    "State Forest Service Road": "St FS Rd",
    "State Highway": "State Hwy",
    "State Loop": "State Loop",
    "State Road": "State Rd",
    "State Route": "State Rte",
    "State Spur": "State Spur",
    "State Trunk Highway": "St Trunk Hwy",
    "Terrace": "Ter",
    "Town Highway": "Town Hwy",
    "Town Road": "Town Rd",
    "Township Highway": "Twp Hwy",
    "Township Road": "Twp Rd",
    "Trail": "Trl",
    "Tribal Road": "Tribal Rd",
    "Tunnel": "Tunl",
    "US Forest Service Highway": "USFS Hwy",
    "US Forest Service Road": "USFS Rd",
    "US Highway": "US Hwy",
    "US Route": "US Rte",
    "Vereda": "Ver",
    "Via": "Via",
    "Vista": "Vis",
}


# Alternate prefix street types (USPS accepted variants)
PREFIX_ALTERNATE = {
    "Av": "Ave",
    "Aven": "Ave",
    "Avenu": "Ave",
    "Avenue": "Ave",
    "Avn": "Ave",
    "Avnue": "Ave",
    "Boul": "Blvd",
    "Boulv": "Blvd",
    "Bypa": "Byp",
    "Bypas": "Byp",
    "Byps": "Byp",
    "Crt": "Ct",
    "Exp": "Expy",
    "Expr": "Expy",
    "Express": "Expy",
    "Expw": "Expy",
    "Highwy": "Hwy",
    "Hiway": "Hwy",
    "Hiwy": "Hwy",
    "Hway": "Hwy",
    "Lanes": "Ln",
    "Loops": "Loop",
    "Plza": "Plz",
    "Sqr": "Sq",
    "Sqre": "Sq",
    "Squ": "Sq",
    "Terr": "Ter",
    "Tr": "Trl",
    "Trails": "Trl",
    "Trls": "Trl",
    "Tunel": "Tunl",
    "Tunls": "Tunl",
    "Tunnels": "Tunl",
    "Tunnl": "Tunl",
    "Vdct": "Via",
    "Viadct": "Via",
    "Viaduct": "Via",
    "Vist": "Vis",
    "Vst": "Vis",
    "Vsta": "Vis"
}


# Merged prefix types (canonical + alternates)
PREFIX_TYPE = TwoWayMap({**PREFIX_CANONICAL, **PREFIX_ALTERNATE})


# Canonical suffix street types from TIGER/Line documentation
SUFFIX_CANONICAL = {
    "Alley": "Aly",
    "Arcade": "Arc",
    "Avenida": "Ave",
    "Avenue": "Ave",
    "Beltway": "Beltway",
    "Boulevard": "Blvd",
    "Bridge": "Brg",
    "Bypass": "Byp",
    "Causeway": "Cswy",
    "Circle": "Cir",
    "Common": "Cmn",
    "Commons": "Cmns",
    "Corners": "Cors",
    "Court": "Ct",
    "Courts": "Cts",
    "Crescent": "Cres",
    "Crest": "Crst",
    "Crossing": "Xing",
    "Cutoff": "Cutoff",
    "Drive": "Dr",
    "Driveway": "Driveway",
    "Esplanade": "Esplanade",
    "Estates": "Ests",
    "Expressway": "Expy",
    "Forest Highway": "Forest Hwy",
    "Fork": "Frk",
    "Four-Wheel Drive Trail": "4WD Trl",
    "Freeway": "Fwy",
    "Grade": "Grade",
    "Heights": "Hts",
    "Highway": "Hwy",
    "Jeep Trail": "Jeep Trl",
    "Landing": "Lndg",
    "Lane": "Ln",
    "Loop": "Loop",
    "Motorway": "Mtwy",
    "Park": "Park",
    "Parkway": "Pkwy",
    "Pass": "Pass",
    "Path": "Path",
    "Pike": "Pike",
    "Place": "Pl",
    "Plaza": "Plz",
    "Point": "Pt",
    "Port": "Prt",
    "Ranch": "Rnch",
    "Ramp": "Ramp",
    "Rest": "Rst",
    "Ridge": "Rdg",
    "Rise": "Rise",
    "Road": "Rd",
    "Route": "Rte",
    "Row": "Row",
    "Skyway": "Skwy",
    "Spring": "Spg",
    "Square": "Sq",
    "Station": "Sta",
    "Street": "St",
    "Terrace": "Ter",
    "Throughway": "Trwy",
    "Trace": "Trce",
    "Track": "Trak",
    "Trail": "Trl",
    "Tunnel": "Tunl",
    "Turnpike": "Tpke",
    "Valley": "Vly",
    "Viaduct": "Via",
    "View": "Vw",
    "Village": "Vlg",
    "Walk": "Walk",
    "Way": "Way",
    "Wells": "Wls",
}


# Alternate suffix street types (USPS accepted variants)
SUFFIX_ALTERNATE = {
    "Aly": "Alley",
    "Anex": "Annex",
    "Annex": "Annex",
    "Annx": "Annex",
    "Arc": "Arcade",
    "Av": "Ave",
    "Aven": "Ave",
    "Avenu": "Ave",
    "Avenue": "Ave",
    "Avn": "Ave",
    "Avnue": "Ave",
    "Bayoo": "Bayou",
    "Bayou": "Bayou",
    "Bch": "Beach",
    "Beach": "Beach",
    "Bend": "Bend",
    "Bg": "Burg",
    "Bgs": "Burgs",
    "Blf": "Bluff",
    "Blfs": "Bluffs",
    "Bluf": "Bluff",
    "Bluff": "Bluff",
    "Bluffs": "Bluffs",
    "Blvd": "Blvd",
    "Bnd": "Bend",
    "Bot": "Bottom",
    "Bottm": "Bottom",
    "Bottom": "Bottom",
    "Boul": "Blvd",
    "Boulv": "Blvd",
    "Br": "Branch",
    "Branch": "Branch",
    "Brdge": "Bridge",
    "Brg": "Bridge",
    "Bridge": "Bridge",
    "Brk": "Brook",
    "Brks": "Brooks",
    "Brook": "Brook",
    "Brooks": "Brooks",
    "Burg": "Burg",
    "Burgs": "Burgs",
    "Byp": "Byp",
    "Bypa": "Byp",
    "Bypas": "Byp",
    "Bypass": "Byp",
    "Byps": "Byp",
    "Byu": "Bayou",
    "Camp": "Camp",
    "Canyn": "Canyon",
    "Canyon": "Canyon",
    "Cape": "Cape",
    "Causeway": "Cswy",
    "Causwa": "Cswy",
    "Cen": "Center",
    "Cent": "Center",
    "Center": "Center",
    "Centers": "Centers",
    "Centr": "Center",
    "Centre": "Center",
    "Cir": "Cir",
    "Circ": "Cir",
    "Circl": "Cir",
    "Circle": "Cir",
    "Circles": "Circles",
    "Cirs": "Circles",
    "Ck": "Creek",
    "Clf": "Cliff",
    "Clfs": "Cliffs",
    "Cliff": "Cliff",
    "Cliffs": "Cliffs",
    "Clb": "Club",
    "Club": "Club",
    "Cmn": "Cmn",
    "Cmns": "Cmns",
    "Cmp": "Camp",
    "Cnter": "Center",
    "Cntr": "Center",
    "Cnyn": "Canyon",
    "Common": "Cmn",
    "Commons": "Cmns",
    "Cor": "Corner",
    "Corner": "Corner",
    "Corners": "Cors",
    "Cors": "Cors",
    "Course": "Course",
    "Court": "Ct",
    "Courts": "Cts",
    "Cove": "Cove",
    "Coves": "Coves",
    "Cp": "Camp",
    "Cpe": "Cape",
    "Cr": "Creek",
    "Crcl": "Cir",
    "Crcle": "Cir",
    "Crecent": "Cres",
    "Creek": "Creek",
    "Cres": "Cres",
    "Crescent": "Cres",
    "Crest": "Crst",
    "Crk": "Creek",
    "Crossing": "Xing",
    "Crossroad": "Xrd",
    "Crossroads": "Xrds",
    "Crse": "Course",
    "Crsent": "Cres",
    "Crsnt": "Cres",
    "Crssng": "Xing",
    "Crst": "Crst",
    "Crt": "Ct",
    "Cswy": "Cswy",
    "Ct": "Ct",
    "Ctr": "Center",
    "Ctrs": "Centers",
    "Cts": "Cts",
    "Curv": "Curve",
    "Curve": "Curve",
    "Cv": "Cove",
    "Cvs": "Coves",
    "Cyn": "Canyon",
    "Dale": "Dale",
    "Dam": "Dam",
    "Div": "Divide",
    "Divide": "Divide",
    "Dl": "Dale",
    "Dm": "Dam",
    "Dr": "Dr",
    "Driv": "Dr",
    "Drive": "Dr",
    "Drives": "Drives",
    "Drs": "Drives",
    "Drv": "Dr",
    "Dv": "Divide",
    "Dvd": "Divide",
    "Est": "Estate",
    "Estate": "Estate",
    "Estates": "Ests",
    "Ests": "Ests",
    "Exp": "Expy",
    "Expr": "Expy",
    "Express": "Expy",
    "Expressway": "Expy",
    "Expw": "Expy",
    "Expy": "Expy",
    "Ext": "Extension",
    "Extension": "Extension",
    "Extensions": "Extensions",
    "Extn": "Extension",
    "Extnsn": "Extension",
    "Exts": "Extensions",
    "Fall": "Fall",
    "Falls": "Falls",
    "Ferry": "Ferry",
    "Field": "Field",
    "Fields": "Fields",
    "Flat": "Flat",
    "Flats": "Flats",
    "Fld": "Field",
    "Flds": "Fields",
    "Fls": "Falls",
    "Flt": "Flat",
    "Flts": "Flats",
    "Ford": "Ford",
    "Fords": "Fords",
    "Forest": "Forest",
    "Forests": "Forests",
    "Forg": "Forge",
    "Forge": "Forge",
    "Forges": "Forges",
    "Fork": "Frk",
    "Forks": "Forks",
    "Fort": "Fort",
    "Frd": "Ford",
    "Frds": "Fords",
    "Freeway": "Fwy",
    "Freewy": "Fwy",
    "Frg": "Forge",
    "Frgs": "Forges",
    "Frk": "Frk",
    "Frks": "Forks",
    "Frry": "Ferry",
    "Frst": "Forest",
    "Frt": "Fort",
    "Frway": "Fwy",
    "Frwy": "Fwy",
    "Fry": "Ferry",
    "Ft": "Fort",
    "Fwy": "Fwy",
    "Garden": "Garden",
    "Gardens": "Gardens",
    "Gardn": "Garden",
    "Gateway": "Gateway",
    "Gatewy": "Gateway",
    "Gatway": "Gateway",
    "Gdn": "Garden",
    "Gdns": "Gardens",
    "Glen": "Glen",
    "Glens": "Glens",
    "Gln": "Glen",
    "Glns": "Glens",
    "Grden": "Garden",
    "Grdn": "Garden",
    "Grdns": "Gardens",
    "Green": "Green",
    "Greens": "Greens",
    "Grn": "Green",
    "Grns": "Greens",
    "Grov": "Grove",
    "Grove": "Grove",
    "Groves": "Groves",
    "Grv": "Grove",
    "Grvs": "Groves",
    "Gtway": "Gateway",
    "Gtwy": "Gateway",
    "Harb": "Harbor",
    "Harbor": "Harbor",
    "Harbors": "Harbors",
    "Harbr": "Harbor",
    "Haven": "Haven",
    "Havn": "Haven",
    "Hbr": "Harbor",
    "Hbrs": "Harbors",
    "Heights": "Hts",
    "Highway": "Hwy",
    "Highwy": "Hwy",
    "Hill": "Hill",
    "Hills": "Hills",
    "Hiway": "Hwy",
    "Hiwy": "Hwy",
    "Hl": "Hill",
    "Hllw": "Hollow",
    "Hls": "Hills",
    "Hollow": "Hollow",
    "Hollows": "Hollows",
    "Holw": "Hollow",
    "Holws": "Hollows",
    "Hrbor": "Harbor",
    "Ht": "Hts",
    "Hts": "Hts",
    "Hvn": "Haven",
    "Hway": "Hwy",
    "Hwy": "Hwy",
    "Inlet": "Inlet",
    "Inlt": "Inlet",
    "Is": "Island",
    "Island": "Island",
    "Islands": "Islands",
    "Isle": "Isle",
    "Isles": "Isles",
    "Islnd": "Island",
    "Islnds": "Islands",
    "Iss": "Islands",
    "Jct": "Junction",
    "Jction": "Junction",
    "Jctn": "Junction",
    "Jctns": "Junctions",
    "Jcts": "Junctions",
    "Junction": "Junction",
    "Junctions": "Junctions",
    "Junctn": "Junction",
    "Juncton": "Junction",
    "Key": "Key",
    "Keys": "Keys",
    "Knl": "Knoll",
    "Knls": "Knolls",
    "Knol": "Knoll",
    "Knoll": "Knoll",
    "Knolls": "Knolls",
    "Ky": "Key",
    "Kys": "Keys",
    "Lake": "Lake",
    "Lakes": "Lakes",
    "Land": "Land",
    "Landing": "Lndg",
    "Lane": "Ln",
    "Lanes": "Ln",
    "Lck": "Lock",
    "Lcks": "Locks",
    "Ldg": "Lodge",
    "Ldge": "Lodge",
    "Lf": "Loaf",
    "Lgt": "Light",
    "Lgts": "Lights",
    "Light": "Light",
    "Lights": "Lights",
    "Lk": "Lake",
    "Lks": "Lakes",
    "Ln": "Ln",
    "Lndg": "Lndg",
    "Lndng": "Lndg",
    "Loaf": "Loaf",
    "Lock": "Lock",
    "Locks": "Locks",
    "Lodg": "Lodge",
    "Lodge": "Lodge",
    "Loop": "Loop",
    "Loops": "Loop",
    "Mall": "Mall",
    "Manor": "Manor",
    "Manors": "Manors",
    "Mdw": "Meadow",
    "Mdws": "Meadows",
    "Meadow": "Meadow",
    "Meadows": "Meadows",
    "Medows": "Meadows",
    "Mews": "Mews",
    "Mill": "Mill",
    "Mills": "Mills",
    "Mission": "Mission",
    "Missn": "Mission",
    "Ml": "Mill",
    "Mls": "Mills",
    "Mnr": "Manor",
    "Mnrs": "Manors",
    "Mnt": "Mount",
    "Mntain": "Mountain",
    "Mntn": "Mountain",
    "Mntns": "Mountains",
    "Motorway": "Mtwy",
    "Mount": "Mount",
    "Mountain": "Mountain",
    "Mountains": "Mountains",
    "Mountin": "Mountain",
    "Msn": "Mission",
    "Mssn": "Mission",
    "Mt": "Mount",
    "Mtin": "Mountain",
    "Mtn": "Mountain",
    "Mtns": "Mountains",
    "Mtwy": "Mtwy",
    "Nck": "Neck",
    "Neck": "Neck",
    "Opas": "Overpass",
    "Orch": "Orchard",
    "Orchard": "Orchard",
    "Orchrd": "Orchard",
    "Oval": "Oval",
    "Overpass": "Overpass",
    "Ovl": "Oval",
    "Park": "Park",
    "Parks": "Parks",
    "Parkway": "Pkwy",
    "Parkways": "Parkways",
    "Parkwy": "Pkwy",
    "Pass": "Pass",
    "Passage": "Psge",
    "Path": "Path",
    "Paths": "Path",
    "Pike": "Pike",
    "Pikes": "Pike",
    "Pine": "Pine",
    "Pines": "Pines",
    "Pk": "Park",
    "Pkway": "Pkwy",
    "Pkwy": "Pkwy",
    "Pkwys": "Parkways",
    "Pky": "Pkwy",
    "Pl": "Pl",
    "Place": "Pl",
    "Plain": "Plain",
    "Plains": "Plains",
    "Plaza": "Plz",
    "Pln": "Plain",
    "Plns": "Plains",
    "Plz": "Plz",
    "Plza": "Plz",
    "Pne": "Pine",
    "Pnes": "Pines",
    "Point": "Pt",
    "Points": "Points",
    "Port": "Prt",
    "Ports": "Ports",
    "Pr": "Prairie",
    "Prairie": "Prairie",
    "Prk": "Park",
    "Prr": "Prairie",
    "Prt": "Prt",
    "Prts": "Ports",
    "Psge": "Psge",
    "Pt": "Pt",
    "Pts": "Points",
    "Rad": "Radial",
    "Radial": "Radial",
    "Radiel": "Radial",
    "Radl": "Radial",
    "Ramp": "Ramp",
    "Ranch": "Rnch",
    "Ranches": "Ranches",
    "Rapid": "Rapid",
    "Rapids": "Rapids",
    "Rd": "Rd",
    "Rdg": "Rdg",
    "Rdge": "Rdg",
    "Rdgs": "Ridges",
    "Rds": "Roads",
    "Rest": "Rst",
    "Ridge": "Rdg",
    "Ridges": "Ridges",
    "Rise": "Rise",
    "Riv": "River",
    "River": "River",
    "Rivr": "River",
    "Rnch": "Rnch",
    "Rnchs": "Ranches",
    "Road": "Rd",
    "Roads": "Roads",
    "Route": "Rte",
    "Row": "Row",
    "Rpd": "Rapid",
    "Rpds": "Rapids",
    "Rst": "Rst",
    "Rte": "Rte",
    "Rue": "Rue",
    "Run": "Run",
    "Rvr": "River",
    "Shl": "Shoal",
    "Shls": "Shoals",
    "Shoal": "Shoal",
    "Shoals": "Shoals",
    "Shoar": "Shore",
    "Shoars": "Shores",
    "Shore": "Shore",
    "Shores": "Shores",
    "Shr": "Shore",
    "Shrs": "Shores",
    "Skwy": "Skwy",
    "Skyway": "Skwy",
    "Smt": "Summit",
    "Spg": "Spg",
    "Spgs": "Springs",
    "Spng": "Spg",
    "Spngs": "Springs",
    "Spring": "Spg",
    "Springs": "Springs",
    "Sprng": "Spg",
    "Sprngs": "Springs",
    "Spur": "Spur",
    "Spurs": "Spur",
    "Sq": "Sq",
    "Sqr": "Sq",
    "Sqre": "Sq",
    "Sqrs": "Squares",
    "Sqs": "Squares",
    "Squ": "Sq",
    "Square": "Sq",
    "Squares": "Squares",
    "St": "St",
    "Sta": "Sta",
    "Station": "Sta",
    "Statn": "Sta",
    "Stn": "Sta",
    "Str": "St",
    "Stra": "Stra",
    "Strav": "Stra",
    "Strave": "Stra",
    "Straven": "Stra",
    "Stravenue": "Stra",
    "Stravn": "Stra",
    "Stream": "Stream",
    "Street": "St",
    "Streets": "Streets",
    "Streme": "Stream",
    "Strm": "Stream",
    "Strt": "St",
    "Strvn": "Stra",
    "Strvnue": "Stra",
    "Sts": "Streets",
    "Sumit": "Summit",
    "Sumitt": "Summit",
    "Summit": "Summit",
    "Smt": "Summit",
    "Ter": "Ter",
    "Terr": "Ter",
    "Terrace": "Ter",
    "Throughway": "Trwy",
    "Tpke": "Tpke",
    "Tr": "Trl",
    "Trace": "Trce",
    "Traces": "Trce",
    "Track": "Trak",
    "Tracks": "Trak",
    "Trafficway": "Trfy",
    "Trail": "Trl",
    "Trailer": "Trlr",
    "Trails": "Trl",
    "Trak": "Trak",
    "Trce": "Trce",
    "Trfy": "Trfy",
    "Trk": "Trak",
    "Trks": "Trak",
    "Trl": "Trl",
    "Trlr": "Trlr",
    "Trlrs": "Trlrs",
    "Trls": "Trl",
    "Trnpk": "Tpke",
    "Trwy": "Trwy",
    "Tunel": "Tunl",
    "Tunl": "Tunl",
    "Tunls": "Tunl",
    "Tunnel": "Tunl",
    "Tunnels": "Tunl",
    "Tunnl": "Tunl",
    "Turnpike": "Tpke",
    "Turnpk": "Tpke",
    "Un": "Union",
    "Underpass": "Unp",
    "Union": "Union",
    "Unions": "Unions",
    "Unp": "Unp",
    "Uns": "Unions",
    "Upas": "Unp",
    "Valley": "Vly",
    "Valleys": "Valleys",
    "Vally": "Vly",
    "Vdct": "Via",
    "Via": "Via",
    "Viadct": "Via",
    "Viaduct": "Via",
    "View": "Vw",
    "Views": "Views",
    "Vill": "Village",
    "Villag": "Village",
    "Village": "Vlg",
    "Villages": "Villages",
    "Ville": "Ville",
    "Villg": "Village",
    "Villiage": "Village",
    "Vist": "Vis",
    "Vista": "Vis",
    "Vl": "Ville",
    "Vlg": "Vlg",
    "Vlgs": "Villages",
    "Vlly": "Vly",
    "Vly": "Vly",
    "Vlys": "Valleys",
    "Vst": "Vis",
    "Vsta": "Vis",
    "Vw": "Vw",
    "Vws": "Views",
    "Walk": "Walk",
    "Walks": "Walks",
    "Wall": "Wall",
    "Way": "Way",
    "Ways": "Ways",
    "Well": "Well",
    "Wells": "Wls",
    "Wl": "Well",
    "Wls": "Wls",
    "Wy": "Way",
    "Xing": "Xing",
    "Xrd": "Xrd",
    "Xrds": "Xrds",
}


# Merged suffix types (canonical + alternates)
SUFFIX_TYPE = TwoWayMap({**SUFFIX_CANONICAL, **SUFFIX_ALTERNATE})


# US States and territories
STATE = TwoWayMap({
    "Alabama": "AL",
    "Alaska": "AK",
    "American Samoa": "AS",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Federated States of Micronesia": "FM",
    "Florida": "FL",
    "Georgia": "GA",
    "Guam": "GU",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Marshall Islands": "MH",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Northern Mariana Islands": "MP",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Palau": "PW",
    "Pennsylvania": "PA",
    "Puerto Rico": "PR",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virgin Islands": "VI",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY"
})
